<?php

return [
    'community_acronym'             => 'DEMO',
    'community_long_name'           => 'ANYTD Tres Dias',
    'local_community_filter'        => 'DEMO',

    'retreat_name_for_email_subject'=> 'Tres Dias Retreat',
    'email_general'                 => null,
    'email-preweekend-mailbox'      => null,
    'email-postweekend-mailbox'     => null,
    'email-palanca-mailbox'         => null,
    'email-finance-mailbox'         => null,
    'facebook_page'                 => 'https://www.facebook.com/groups/',
    'newsletter_archive_url'        => null,
    'reunion_groups_google_sheet_url' => null,
    'community_mailing_address'     => "",
    'community_mailing_address_for_payments' => '',
    'candidate_fee_text_for_emails' => '$200 per person',
    'camp-weather-forecast'         => 'The weather is typically warm, with possible rain.',
    'emergency_contact_text'        => '',
    'emergency_contact_number'      => '',
    'notify_UserAdded1'             => null,
    'notify_UserDeleted1'           => null,
    'notify_PrayerWheelChanges'     => null,
    'notify_CandidateAdded1'        => null,
    'notify_CandidateDeleted1'      => null,
    'notify_TeamfeePayments1'       => null,
    'team_fees_spiritual_directors_pay' => false,
    'notify_PreWeekend_of_NewCandidate_When'=> 'sponsor_acknowledgement_sent', // sponsor_acknowledgement_sent or initial_data_entry
    'prayerwheel_empty_before_doubles' => 4,
    'prayerwheel_names_visible_to_all' => false,
    'members_username_default'      => 'Email Address', // Email-Address or FirstLast
    'members_may_edit_own_name'     => false,
    'members_may_edit_own_sponsor'  => false,
    'members_may_edit_own_spouse'   => false,
    'pagination_threshold'          => 25,
    'admin_old_weekend_teams_editable' => false,
    'weekend_shows_finished_for_x_days' => 6,
    'community_SA_may_assign_SDs'   => false,
    'preweekend_does_physical_mailing' => true,
    'features-emailtypes-reunion'   => true,
    'preweekend_sponsor_confirmations_enabled' => true,
    'admin_must_approve_new_members' => false,

    'map_url'                       => 'https://www.google.com/maps/preview?q=',
    'candidate_application_url'     => '/TD_Candidate_Application.pdf',
    'file_letters_sample'           => 'Tres Dias Request for family letters generic.docx',
    'file_sponsor_responsibilities' => 'Sponsor Responsibilities.pdf',

    'template_logo_url'             => null,

    'payments_email_transfer_address' => null,
    'payments_paypal_hosted_button_id' => null,
    'payments_stripe_pkey'          => 'demo',
    'payments_stripe_currencies'    => 'USD',

    'notify_UserAdded2'             => null,
    'notify_UserDeleted2'           => null,
    'notify_CandidateAdded2'        => null,
    'notify_CandidateDeleted2'      => null,
    'notify_TeamfeePayments2'       => null,
];
